In [1]:
import audio_augmentation as aa

In [2]:
import torch
import torchaudio
import numpy as np

In [3]:
waveform, sample_rate = torchaudio.load('data/test_viole_2.wav')

In [4]:
mfcc_transform = torchaudio.transforms.MFCC(
    sample_rate=sample_rate
)

lms_transform = torchaudio.transforms.MelSpectrogram(
    sample_rate=sample_rate
)

/home/roman/.local/lib/python3.10/site-packages/torchaudio/functional/functional.py:584: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(


In [5]:
mfcc = mfcc_transform(waveform)
lms = lms_transform(waveform)

In [6]:
# normalize lms
lms = torch.log(lms + 1e-9)

lms -= lms.mean()
lms /= (lms.std() + 1e-6)

lms = lms.float()

### Check functions

#### MFCC

In [7]:
mfcc[0, 0]

tensor([-328.9099, -267.8841, -224.3265,  ..., -290.2507, -295.1046,
        -373.5463])

In [8]:
mfcc.shape

torch.Size([2, 40, 3529])

In [9]:
aug_mfcc = aa.augment_mfcc(
    mfcc=mfcc, sample_rate=sample_rate, speed_factor=0.5, 
    freq_start_remove=10, freq_end_remove=20, noise=0.02
)

In [10]:
aug_mfcc[0, 0]

tensor([-234.0032, -248.1602, -168.3893,  ..., -283.0197, -308.9566,
        -260.4059])

In [11]:
aug_mfcc.shape

torch.Size([2, 30, 1765])

In [12]:
aug_mfcc = aa.augment_mfcc(
    mfcc=mfcc, time_start_remove=100, time_end_remove=200,
    freq_start_remove=10, freq_end_remove=20, noise=0.02
)

In [13]:
aug_mfcc.shape

torch.Size([2, 30, 3429])

### LogMelSpectrogran

In [14]:
lms[0, 0]

tensor([-2.2058, -2.2058, -2.2058,  ..., -2.2058, -2.2058, -2.2058])

In [15]:
lms.shape

torch.Size([2, 128, 3529])

In [16]:
aug_lms = aa.augment_logmel_spectrogram(
    logmel_spec=lms, speed_factor=0.5, freq_start_remove=10, 
    freq_end_remove=20, noise=0.02
)

In [17]:
aug_lms[0, 0]

tensor([-2.2146, -2.2173, -2.2309,  ..., -2.2107, -2.1689, -2.2039])

In [18]:
aug_lms.shape

torch.Size([2, 118, 1764])

In [19]:
aug_lms = aa.augment_logmel_spectrogram(
    logmel_spec=lms, speed_factor=0.5, time_start_remove=100,
    time_end_remove=200, freq_start_remove=10, freq_end_remove=20,
    noise=0.02
)

In [20]:
aug_lms.shape

torch.Size([2, 118, 1664])